pipeline:

  #build:
  #  image: banian/node
  #  commands:
  #      - NODE_ENV=production yarn
  #      - NODE_ENV=production yarn prod

  publish:
    image: plugins/docker
    mirror: http://mirror.docker.cloud.aut.ac.ir
    registry: registry.docker.cloud.aut.ac.ir
    repo: registry.docker.cloud.aut.ac.ir/autrevised/autrevised
    secrets: [ docker_username, docker_password ]
    tag: latest
    when:
      branch: master
      event: push
